import { fromUnixTime } from "date-fns"

export { default as LoginScreen} from "./Login"
export { default as CadastrarScreen} from "./Cadastrar"
export { default as PerfilScreen} from "./Perfil"
export { default as MapScreen} from "./Map"
export { default as SairScreen} from "./Sair"
export {default as QrCodeScreen} from "./QrCode"
export {default as CameraScreen} from "./Camera"
export {default as ArquivoScreen} from "./Arquivo"
export {default as VideoAudioScreen} from "./VideoAudio"
export {default as AcelerometroScreen} from "./Acelerometro"
export {default as PedometroScreen } from "./Pedometro"
export {default as MagnetoScreen } from "./Magneto"
export {default as GiroscopioScreen } from "./Giroscopio"