export { default as LoginScreen } from './Login'
export { default as CadastrarScreen } from './Cadastrar'
export { default as PerfilScreen } from "./Perfil"
export { default as ChatScreen } from "./Chat"
export { default as MapScreen } from "./Map"
export { default as SairScreen } from "./Sair"
export { default as QrCodeScreen } from "./QrCode"
export { default as CameraScreen } from "./Camera"
export { default as ArquivoScreen } from "./Arquivo"